on:
  push:
    tags:
      - 'v*'
jobs:
  examplejob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Notify new release on Slack
        uses: italia/slack-notify-release-action@v0.4.0
        with:
          slack_token: 9cYo1uThhm8TizDNWakgODzh
          channel_id: C05374Z8C6M
          project_name: Trios Desktop app
